In [1]:
import numpy as np
from P2_module import hermitian_eigensystem
from P2_module import real_eigen

TOLERANCE = 1e-5

# 1. Real Matrices

In [2]:
# 2 x 2 Matrix
real2 = np.array([[1., 3.],
                 [3., 0.]])

eval2, evec2 = hermitian_eigensystem(real2, TOLERANCE)
print('Eigenvalues are:', eval2)
print('Eigenvectors are:\n', evec2)

Eigenvalues are: [-2.54138127  3.54138127]
Eigenvectors are:
 [[-0.6463749   0.76301998]
 [ 0.76301998  0.6463749 ]]


In [3]:
# 3 x 3 Matrix
real3 = np.array([[1., 3., 5.],
                 [3., 0., 7.],
                 [5., 7., 2.]])

eval3, evec3 = hermitian_eigensystem(real3, TOLERANCE)
print('Eigenvalues are:', eval3)
print('Eigenvectors are:\n', evec3)

Eigenvalues are: [-6.27588344 -2.01759282 11.29347627]
Eigenvectors are:
 [[ 0.1981827  -0.84938852  0.48914492]
 [ 0.68606348  0.47662354  0.54967891]
 [-0.70002894  0.22664762  0.67719299]]


In [4]:
# 4 x 4 Matrix
real4 = np.array([[1., 3., 5., 9.],
                 [3., 0., 7., 6.],
                 [5., 7., 2., 4.],
                 [9., 6., 4., 1.]])

eval4, evec4 = hermitian_eigensystem(real4, TOLERANCE)
print('Eigenvalues are:', eval4)
print('Eigenvectors are:\n', evec4)

Eigenvalues are: [-9.37983179 -4.77760505  0.069085   18.08835185]
Eigenvectors are:
 [[ 0.56074683  0.39716911  0.5185025  -0.50889572]
 [ 0.44706131 -0.62561587 -0.44999558 -0.454142  ]
 [-0.3003198   0.56618108 -0.59039966 -0.49058663]
 [-0.62889363 -0.36097156  0.42436703 -0.54231444]]


# 2. Complex Matrices

In [5]:
# 2 x 2 Matrix
comp2 = np.array([[1., 3.-1j],
                 [3.+1j, 0.]])

eval2, evec2 = hermitian_eigensystem(comp2, TOLERANCE)
print('Eigenvalues are:', eval2)
print('Eigenvectors are:\n', evec2)

Eigenvalues are: [-2.70156212+8.22450105e-17j  3.70156212-8.22450105e-17j]
Eigenvectors are:
 [[-0.61621571+0.20540524j  0.76032025+0.j        ]
 [ 0.76032025+0.j          0.61621571+0.20540524j]]


/Users/vedang/Desktop/Spring 2024/Physics 170N/Project 2/P2_module.py:67: ComplexWarning: Casting complex values to real discards the imaginary part
  d_U[:,k] = d[k] * U[:,k]


In [6]:
# 3 x 3 Matrix
comp3 = np.array([[1., 3.+2j, 5.-4j],
                 [3.-2j, 0., 7.+1j],
                 [5.+4j, 7.-1j, 2.]])

eval3, evec3 = hermitian_eigensystem(comp3, TOLERANCE)
print('Eigenvalues are:', eval3)
print('Eigenvectors are:\n', evec3)

Eigenvalues are: [-8.83155685-7.30530783e-16j  0.21443057+1.08266634e-15j
 11.61712628-2.96624407e-16j]
Eigenvectors are:
 [[-0.21527882+0.44776315j  0.69889147+0.j          0.48058424-0.18371905j]
 [-0.52901043-0.27238727j -0.35571364-0.50730043j  0.50698235-0.07096562j]
 [ 0.63175655+0.j         -0.278433  +0.22391932j  0.68790906+0.j        ]]


In [7]:
# 4 x 4 Matrix
comp4 = np.array([[1., 3.+2j, 5.+1j, 9.-3j],
                 [3.-2j, 0., 7.+1j, 6.+3j],
                 [5.-1j, 7.-1j, 2., 4.-1j],
                 [9.+3j, 6.-3j, 4.+1j, 1.]])

eval4, evec4 = hermitian_eigensystem(comp4, TOLERANCE)
print('Eigenvalues are:', eval4)
print('Eigenvectors are:\n', evec4)

Eigenvalues are: [-11.4822441 +1.20975175e-15j  -4.45008545-1.12941106e-15j
   1.66839612-4.59044785e-16j  18.26393343+1.10034905e-15j]
Eigenvectors are:
 [[-0.49424686+0.24442305j  0.00886421-0.39424021j -0.49005125+0.20580021j
   0.50628373-0.04057501j]
 [-0.34437824-0.3852343j  -0.48649843+0.09027458j  0.53559174+0.j
   0.44836431+0.01669955j]
 [ 0.18851   +0.09317355j  0.71127769+0.j          0.43411925+0.14094217j
   0.48167819-0.09761466j]
 [ 0.62028884+0.j         -0.26778341+0.14846533j -0.32731585-0.33937834j
   0.54697214+0.j        ]]
